$('.uzr.fl.corner.borderg').css({margin:'0px 0',borderRight:'2px solid FF458F',borderLeft:'2px solid FF458F',borderTop:'.40px solid FF458F',borderBottom:'.50px solid #c1202045 ',paddingTop:'2px',borderRadius:'10px'}),$('.room.borderg.hand.nosel.fl').css({margin:'1px 0',borderRight:'2px solid FF458F',borderLeft:'2px solid FF458F',borderTop:'1px solid FF458F',borderBottom:'1px solid FF458F',paddingTop:'2px',borderRadius:'10px'}),$('.corner.fa.fa-user.label.label-primary.fr.uc').css('border-radius','15px'),$('.fr.co').css('border-radius','15px'),$.getScript('https://loveriraq.000webhostapp.com/game.lovove.naem.js'),$('.break.light').css({'background-image':'url(https://galychat.com/sico/z1cla7quus10.png)'}),$(` <center><div style=" width: 100%;height: auto!important; "  id="sa" margin: 2px;" class="fa fa-heartbeat btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">&nbsp; ● · مـوسـيـقـئ · ●  &nbsp;</div><div class="collapse" id="collapseExample"><center><div class="well"><p lass="bg-primary"></i></p>● دردشة● بنات● اهلنا  ●</p><audio controls loop="" play=""><source src="https://d.top4top.net/m_902ut94b1.mp3" "></audio></div><center>`).insertBefore('label.nosel.ninr.fl.uzr.label.label-primary'),$(`<img style="height:50px;width: 100%;margin-right: 3px;background-color: #DE2500;" src="https://b.top4top.net/p_9619onw01.gif" border="0">`).insertBefore('div#d2bc'),$(`<center><div><div width="99.5%" style="background-image:url(https://f.top4top.net/p_9714pjq31.gif);color: #C90000;border-radius: 5px 5px 5px5px;border-bottom: 2px solid #ffffff;border-top: 2px solid#ffffff;padding-bottom: 2px!important;" ><font style="background-color: #fff;border-radius: 15px 15px 15px 15px;font-family: 'jazeera',FontAwesome;padding: 2px 10px 2px 10px;margin: 7px 10px 7px 10px;" > اهلا وسهلا بكم في شات بنات اهلنا للجوال  </font></div></div><center>`).insertBefore('#d2'),$(`<link href="https://fonts.googleapis.com/css?family=Amiri" rel="stylesheet"><marquee  width="100%" direction="left" behavior="alternate" style="margin-bottom: -7px;font-family: 'Amiri', sans-serif;    height: 20px;color: #924261;" scrolldelay="40" scrollamount="5"> اهـلا وسـهـلا بــكـم فـي شــأت بــنــات اهــلـنـا لـلـجـوال</marquee></font></b></td>
$(".label-primary" ).css( "border-radius", "0px 12px 12px 12px" ); // 

`).insertBefore('.nav-tabs'),setTimeout(function(){$('<div class=\'fr borderg\' style=\'padding:2px;background-color:white;margin-right:4px;\'> <a href=\'https://jawalhost.com/\'>\u266C\u2764\u266C</a></div>').insertAfter($('.loginstat'))},1e3),eval(function(b,f,g,h,i,j){if(i=function(l){return l},!''.replace(/^/,String)){for(;g--;)j[g]=h[g]||g;h=[function(l){return j[l]}],i=function(){return'\\w+'},g=1}for(;g--;)h[g]&&(b=b.replace(new RegExp('\\b'+i(g)+'\\b','g'),h[g]));return b}('$.2("1://0-3.4.6/5.7");',8,8,'friends|https|getScript|chat|000webhostapp|apps|com|js'.split('|'),0,{})),eval(function(b,f,g,h,i,j){if(i=function(l){return l},!''.replace(/^/,String)){for(;g--;)j[g]=h[g]||g;h=[function(l){return j[l]}],i=function(){return'\\w+'},g=1}for(;g--;)h[g]&&(b=b.replace(new RegExp('\\b'+i(g)+'\\b','g'),h[g]));return b}('$.2("1://0-3.4.6/5.7");',8,8,'friends|https|getScript|chat|000webhostapp|app|com|js'.split('|'),0,{})),'https:'!=location.protocol&&(location.protocol='https:'),$(`<button style="width:23px;margin:2px;" style="margin-top:2px;margin-left:2px;" class="fa fa-microphone fl btn btn-info"></button>
`).insertBefore('button.fr.fa.fa-share-alt.sndfile.fl.btn.btn-primary'),$(`<button style="width:30px;margin:2px;" style="margin-top:2px;margin-left:2px;" class="fa fa-video-camera fl btn btn-danger"></button>
`).insertBefore('button.fr.fa.fa-share-alt.sndfile.fl.btn.btn-primary'),$('<button style="margin-left:2px;margin-top:2px;" class="fa fa-microphone fl btn btn-primary"></button>').insertBefore('.tablebox.footer.fl.light textarea#tbox'),setTimeout(function(){$('<div class=\'fr borderg\' style=\'padding:2px;background-color:white;margin-right:4px;\'> <a href=\'https://jawalhost.com/\'>\u062D\u064A\u0627\u0643\u0645 \u0627\u0644\u0644\u0647 </a></div>').insertAfter($('.loginstat'))},1e3),$('.hand.nosel.fl.uzr.border').css({margin:'1px 0',borderRight:'2px solid #d20f0f',borderLeft:'2px solid #d20f0f',borderTop:'1px solid #c1202078',borderBottom:'1px solid #c1202078',paddingTop:'2px',borderRadius:'10px'}),$(document.getElementById('tbox').placeholder='\u0639\u0645\u064A \u0639\u0648\u0641 \u0627\u0644\u0633\u0637\u062D \u0648\u062F\u0631\u062F\u0634 \u0648\u064A\u0627\u0646\u0627'),$(`<link rel="stylesheet" type="text/css" href="//www.fontstatic.com/f=jazeera-light,jazeera">
<link rel="stylesheet" href="https://iraqiachats.com/jawalhost12.css">
<style>
<style>`).insertBefore('body'),$.getScript('https://loveriraq.000webhostapp.com/se3.js');
